name: Auto Approval
on:
  pull_request:
    types: [opened, reopened]

concurrency:
  group: format('{0}-{1}', ${{ github.ref }}, 'Auto Approval')
  cancel-in-progress: true

jobs:
  auto_approve:
    name: Auto Approve PRs
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Approve PR
        if: ${{ github.event.pull_request.user.login == 'planetscale-actions-bot' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve
