name: check_make_vtadmin_web_proto
on: [push]
jobs:

  build:
    name: Check Make VTAdmin Web Proto
    runs-on: ubuntu-latest
    steps:
    - name: Configure git private repo access
      env:
        GITHUB_TOKEN: ${{ secrets.PLANETSCALE_ACTIONS_BOT_TOKEN }}
      run: |
        git config --global --add url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.2

    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        # node-version should match package.json
        node-version: '16.19.0'

    - name: Install npm dependencies
      run: npm ci
      working-directory: ./web/vtadmin

    - name: check_make_vtadmin_web_proto
      run: |
        tools/check_make_vtadmin_web_proto.sh
